### ISSUE TITLE
Iteration 2.5 - ToDo List

### ISSUE THREAD

**Issue by chalstead16** [chalstead16/sensi#12]
- [ ] As a user, I should be able to see my todo list on page load
- [ ] As a user, I should be able to add tasks
- [ ] As a user, I should be able to check off completed tasks
